<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_invoice_ui_menu() {
  $items = array();

  $items['admin/commerce/invoices/%commerce_invoice'] = array(
    'title' => 'Invoice',
    'page callback' => 'commerce_invoice_ui_invoice_view',
    'page arguments' => array(3),
    'access callback' => 'commerce_invoice_access',
    'access arguments' => array('view', 3),
  );
  $items['admin/commerce/invoices/%commerce_invoice/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/invoices/%commerce_invoice/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'commerce_invoice_ui_invoice_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_invoice_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_invoice_ui.invoices.inc',
  );
  $items['admin/commerce/invoices/%commerce_invoice/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'commerce_invoice_ui_invoice_delete_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_invoice_access',
    'access arguments' => array('delete', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_invoice_ui.invoices.inc',
  );
  $items['admin/commerce/config/invoice'] = array(
    'title' => 'Invoice settings',
    'description' => 'Configure general invoice settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_invoice_settings_form'),
    'access arguments' => array('configure invoice settings'),
    'file' => 'includes/commerce_invoice_ui.invoices.inc',
  );
  $items['admin/commerce/config/invoice/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/commerce/orders/%commerce_order/invoices'] = array(
    'title' => 'Invoices',
    'page callback' => 'commerce_invoice_ui_invoice_view_by_order',
    'page arguments' => array(3),
    'access callback' => 'commerce_invoice_ui_access_by_order',
    'access arguments' => array('view', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['user/%user/invoices/%commerce_invoice'] = array(
    'title callback' => 'commerce_invoice_ui_invoice_title',
    'title arguments' => array(3),
    'page callback' => 'commerce_invoice_ui_invoice_view',
    'page arguments' => array(3, 'customer', FALSE),
    'access callback' => 'commerce_invoice_access',
    'access arguments' => array('view', 3),
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function commerce_invoice_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_invoice_ui') . '/includes/views',
  );
}

/**
 * Menu item title callback: returns the number of an invoice for its pages.
 *
 * @param $invoice
 *   The invoice object as loaded via the URL wildcard.
 * @return
 *   A page title of the format "Invoice ##".
 */
function commerce_invoice_ui_invoice_title($invoice) {
  return t('Invoice @number', array('@number' => $invoice->invoice_number));
}

/**
 * Sets the breadcrumb for invoice pages.
 *
 * @param $view_mode
 *   The view mode for the current invoice page, 'administrator' or 'customer'.
 */
function commerce_invoice_ui_set_breadcrumb($view_mode = 'administrator') {
  $breadcrumb = array();

  // Create the breadcrumb array based on the view mode.
  if ($view_mode == 'administrator') {
    $breadcrumb = array(
      l(t('Home'), '<front>'),
      l(t('Administration'), 'admin'),
      l(t('Store'), 'admin/commerce'),
      l(t('Invoices', array(), array('context' => 'a drupal commerce invoice')), 'admin/commerce/invoices'),
    );
  }

  drupal_set_breadcrumb($breadcrumb);
}

/**
 * Generate an array for rendering the given invoice.
 *
 * @param $invoice
 *   A fully loaded invoice object.
 * @param $view_mode
 *   The view mode for displaying the invoice, 'administrator' or 'customer'.
 *
 * @return
 *   An array as expected by drupal_render().
 */
function commerce_invoice_ui_invoice_view($invoice, $view_mode = 'administrator', $breadcrumb = TRUE) {
  // Set the breadcrumb for the appropriate view mode if specified.
  if ($breadcrumb) {
    commerce_invoice_ui_set_breadcrumb();
  }

  drupal_add_css(drupal_get_path('module', 'commerce_order') . '/theme/commerce_order.css');

  return entity_view('commerce_invoice', array($invoice->invoice_id => $invoice), $view_mode, NULL, TRUE);
}

/**
 * Generate an array for rendering the given invoice, based on an order.
 *
 * @param $order
 *   A fully loaded order object.
 * @param $view_mode
 *   The view mode for displaying the invoice, 'administrator' or 'customer'.
 *
 * @return
 *   An array as expected by drupal_render().
 */
function commerce_invoice_ui_invoice_view_by_order($order, $view_mode = 'administrator', $breadcrumb = TRUE) {

  $query = new EntityFieldQuery();

  $result = $query
    ->entityCondition('entity_type', 'commerce_invoice')
    ->propertyCondition('order_id', $order->order_id)
    ->execute();
  $commerce_invoice_keys = array_keys($result['commerce_invoice']);
  $invoices = array();
  $list = array();
  foreach ($commerce_invoice_keys as $commerce_invoice_key) {
    $invoice = commerce_invoice_load($commerce_invoice_key);
    $supplier_term = taxonomy_term_load($invoice->supplier_tid);
    $list[] = l('Supplier: ' . $supplier_term->name . ' - Invoice nr ' . $invoice->invoice_number . '.', 'admin/commerce/invoices/' . $invoice->invoice_id);
  }
  return theme('item_list', array('items' => $list));

}

/**
 * Checks invoice access based on order id.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param $order
 *   Optionally an order to check access for.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the current user.
 */
function commerce_invoice_ui_access_by_order($op, $order = NULL, $account = NULL) {
  $invoice = commerce_invoice_load_by_order_id($order->order_id);

  if ($invoice) {
    return commerce_invoice_access($op, $invoice, $account, 'commerce_invoice');
  }
  else {
    return FALSE;
  }
}


/**
 * Implements hook commerce_entity_access().
 */
function commerce_invoice_ui_commerce_entity_access($op, $entity, $account, $entity_type) {
  if ($entity_type = 'commerce_order') {
    // Disable updating or deleting invoiced orders.
    if (isset($entity->status) && ($entity->status == 'invoiced')) {
      global $user;
      if (!in_array('administrator', $user->roles)) {
        if ($op == 'update') {
          $invoices = array();
          $invoices = db_select('commerce_invoice', 'ci')
              ->fields('ci', array('invoice_id'))
              ->condition('order_id', $entity->order_id)
              ->execute()
              ->fetchAll();

          if (!empty($invoices)) {
            return FALSE;
          }
        }
        elseif($op == 'delete') {
          return FALSE;
        }
      }
    }
  }
}
