<?php

/**
 * @file
 * Module with adaptations for Monde Des Milles Couleurs
 */

/**
 * Implements hook_form_alter()
 */
function mdmc_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  //Add validation to the 'add product' form to hide/disable fields and autopopulate SKU and Title.
  if ($form_id == 'commerce_product_ui_product_form') {
    if ($form['#entity_type'] == 'commerce_product') {

      $form['sku']['#required'] = FALSE;
      $form['sku']['#disabled'] = TRUE;
      $form['#validate'][] = 'mdmc_add_product_validate';

      if($form['#bundle'] == 'product') {
        $form['sku']['#required'] = FALSE;
        $form['sku']['#disabled'] = TRUE;
        $form['title']['#required'] = FALSE;
        $form['title']['#disabled'] = TRUE;
        $form['#validate'][] = 'mdmc_add_product_validate';
        if ($user->uid != 1) {
          unset($form['language']);
          unset($form['change_history']);
          if (isset($form['#entity']->product_id)) {
            $form['field_product_supplier']['#disabled'] = TRUE;
            $form['field_product_type']['#disabled'] = TRUE;
            $form['field_product_sort']['#disabled'] = TRUE;
            $form['field_product_variation']['#disabled'] = TRUE;
          }
        }
      }
    }
  }
}

/**
 * Implements hook commerce_entity_access().
 */
function mdmc_commerce_entity_access($op, $entity, $account, $entity_type) {
  if ($entity_type = 'commerce_order') {
    // Disable deleting completed orders.
    if (isset($entity->status) && (($op == 'delete') && ($entity->status == 'completed'))) {
      global $user;
      if (!in_array('administrator', $user->roles)) {
        return FALSE;
      }
    }
  }
}

/**
 * Implements hook_action_info.
 * @return type
 */
function mdmc_action_info() {
  //Add vbo actions to set order status
  $action = array(
    'mdmc_set_order_processing' => array(
        'type' => 'commerce_order',
        'label' => t('Set order status: Processing'),
        'configurable' => FALSE,
        'pass rows' => TRUE, // this will ensure that the entire views row is passed as part of the context in your action callback.
        'aggregate' => TRUE,
    ),
    'mdmc_set_order_completed' => array(
        'type' => 'commerce_order',
        'label' => t('Set order status: Completed'),
        'configurable' => FALSE,
        'pass rows' => TRUE, // this will ensure that the entire views row is passed as part of the context in your action callback.
        'aggregate' => TRUE,
    ),
    'mdmc_product_enable' => array(
        'type' => 'commerce_product',
        'label' => t('Set product status: Enabled'),
        'configurable' => FALSE,
        'pass rows' => TRUE, // this will ensure that the entire views row is passed as part of the context in your action callback.
        'aggregate' => TRUE,
    ),
    'mdmc_product_disable' => array(
        'type' => 'commerce_product',
        'label' => t('Set product status: Disabled'),
        'configurable' => FALSE,
        'pass rows' => TRUE, // this will ensure that the entire views row is passed as part of the context in your action callback.
        'aggregate' => TRUE,
    ),
  );
  return $action;
}

/**
 * VBO callback to set orders to processing.
 */
function mdmc_set_order_processing(&$entity, $context = array()) {
  foreach ($entity as $order_id => $order) {
    dsm($order);
    if (($order->status != 'invoiced') && ($order->status != 'merged')) {
      commerce_order_status_update($order, 'processing');
    }
    else {
      drupal_set_message(t("You can't change one or more of these orders."), 'error');
      header("Location: {$_SERVER['HTTP_REFERER']}");
      exit;
    }
  }
}
/**
 * VBO callback to set orders to completed.
 */
function mdmc_set_order_completed(&$entity, $context = array()) {
  foreach ($entity as $order_id => $order) {
    if (($order->status != 'invoiced') && ($order->status != 'merged')) {
      commerce_order_status_update($order, 'completed');
    }
    else {
      drupal_set_message(t("You can't change one or more of these orders."), 'error');
      header("Location: {$_SERVER['HTTP_REFERER']}");
      exit;
    }
  }
}
/**
 * VBO callback to enable products.
 */
function mdmc_product_enable (&$entity, $context = array()) {
  foreach ($entity as $product_id => $product) {
    $product->status = 1;
    commerce_product_save($product);
  }
}
/**
 * VBO callback to disable products.
 */
function mdmc_product_disable (&$entity, $context = array()) {
  foreach ($entity as $product_id => $product) {
    $product->status = 0;
    commerce_product_save($product);
  }
}

/**
 *
 * Function to create product SKU and product title (used in the add-product form)
 * @param type $form
 * @param type $form_state
 */
function mdmc_add_product_validate(&$form, &$form_state) {
  if ($form['#entity_type'] == 'commerce_product') {
    if($form['#bundle'] == 'product') {
      dsm($form_state);
      //Check if values are empty. Get names for taxonomy terms. Create trimmed values and strings.
      if (!empty($form_state['values']['field_product_supplier']['und'][0]['tid'])) {
        $supplier_tid = $form_state['values']['field_product_supplier']['und'][0]['tid'];
        $supplier = taxonomy_term_load($supplier_tid)->name;
        $supplier_trimmed = mdmc_trim_string($supplier, 3);
        $supplier_trimmed_string = $supplier_trimmed . '-';
      } else {
        $supplier = '';
        $supplier_trimmed_string = '';
      }

      if (!empty($form_state['values']['field_product_type']['und'][0]['tid'])) {
        $type_tid = $form_state['values']['field_product_type']['und'][0]['tid'];
        $type = taxonomy_term_load($type_tid)->name;
        $type_trimmed = mdmc_trim_string($type, 4);
        $type_trimmed_string = $type_trimmed . '-';
      } else {
        $type = '';
        $type_trimmed_string = '';
      }

      if (!empty($form_state['values']['field_product_sort']['und'][0]['tid'])) {
        $sort_tid = $form_state['values']['field_product_sort']['und'][0]['tid'];
        $sort = taxonomy_term_load($sort_tid)->name;
        $sort_trimmed = mdmc_trim_string($sort, 4);
        $sort_trimmed_string = $sort_trimmed . '-';
      } else {
        $sort = '';
        $sort_trimmed_string = '';
      }

      if (!empty($form_state['values']['field_product_variation']['und'][0]['name'])) {
        $variation = $form_state['values']['field_product_variation']['und'][0]['name'];
        $variation_array = explode(" ", $variation);
        $variation_trimmed_string = '';
        foreach ($variation_array as $string) {
          $variation_trimmed_string .= mdmc_trim_string($string, 4) . '-';
        }
      } else {
        $variation = '';
        $variation_trimmed_string = '';
      }

      if (!empty($form_state['values']['field_product_unit_number']['und'][0]['value'])) {
        $unit_number = $form_state['values']['field_product_unit_number']['und'][0]['value'] . '-';
      } else {
        $unit_number = ' -';
      }

      if (!empty($form_state['values']['field_product_unit']['und'][0]['tid'])) {
        $unit_tid = $form_state['values']['field_product_unit']['und'][0]['tid'];
        $unit = taxonomy_term_load($unit_tid)->name;
        $unit_trimmed = mdmc_trim_string($unit, 4);
        $unit_trimmed_string = $unit_trimmed;
      } else {
        $unit = '';
        $unit_trimmed_string = '';
      }

      //Build sku and title values and strings.
      $sku = $supplier_trimmed_string . $type_trimmed_string . $sort_trimmed_string . $variation_trimmed_string . $unit_number . $unit_trimmed_string;
      $title = (!empty($sort) ? $sort . ' ' : '') . (!empty($variation) ? $variation . ' ' : '');

    //Set the sku and title value to the form-state
      form_set_value($form['sku'], $sku, $form_state);
      form_set_value($form['title'], $title, $form_state);
    }

    if ($form['#bundle'] == 'empty_case') {
      if (!empty($form_state['values']['title'])) {
        $title = $form_state['values']['title'];
        $title_array = explode(" ", $title);
        $title_trimmed_string = '';
        foreach ($title_array as $string) {
          $title_trimmed_string .= mdmc_trim_string($string, 4) . '-';
        }
      } else {
        $title = '';
        $title_trimmed_string = '';
      }

      //Build sku
      $sku = 'EMPT-CASE-' . $title_trimmed_string;

      //Set the sku
      form_set_value($form['sku'], $sku, $form_state);
    }
    if ($form['#bundle'] == 'promo') {
      if (!empty($form_state['values']['title'])) {
        $title = $form_state['values']['title'];
        $title_array = explode(" ", $title);
        $title_trimmed_string = '';
        foreach ($title_array as $string) {
          $title_trimmed_string .= mdmc_trim_string($string, 4) . '-';
        }
      } else {
        $title = '';
        $title_trimmed_string = '';
      }

      //Build sku
      $sku = 'PROM-' . $title_trimmed_string;

      //Set the sku
      form_set_value($form['sku'], $sku, $form_state);
    }
  }
}

//function to make strings uppercase and trim them.
function mdmc_trim_string($string, $number) {
  if (!empty($string)) {
    if(($number == 0) || (strlen($string) < $number)) {
      $string = strtoupper(preg_replace("/[^a-zA-Z]+/", '', $string));
      return $string;
    }
    else {
      $string = strtoupper(mb_substr(preg_replace("/[^a-zA-Z]+/", '', $string), 0, $number));
      return $string;
    }
  }
}
