<?php

/**
 * @file
 * Module with adaptations for Monde Des Milles Couleurs
 */


/**
 * Implements hook_form_alter()
 */
function mdmc_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  //Add validation to the 'add product' form to hide and autopopulate SKU and Title.
  if ($form_id == 'commerce_product_ui_product_form') {
    $form['sku']['#required'] = FALSE;
    $form['sku']['#disabled'] = TRUE;
    $form['title']['#required'] = FALSE;
    $form['title']['#disabled'] = TRUE;
    $form['#validate'][] = 'mdmc_add_product_validate';
  }
}

/**
 * 
 * Function to create product SKU and product title (used in the add-product form)
 * @param type $form
 * @param type $form_state
 */
function mdmc_add_product_validate(&$form, &$form_state) {
  //Check if values are empty. Get names for taxonomy terms. Create trimmed values and strings.
  if (!empty($form_state['values']['field_product_supplier']['und'][0]['tid'])) {
    $supplier_tid = $form_state['values']['field_product_supplier']['und'][0]['tid'];
    $supplier = taxonomy_term_load($supplier_tid)->name;
    $supplier_trimmed = mdmc_trim_string($supplier, 3);
    $supplier_trimmed_string = $supplier_trimmed . '-';
  } else {
    $supplier = '';
    $supplier_trimmed_string = '';
  }
  if (!empty($form_state['values']['field_product_type']['und'][0]['tid'])) {
    $type_tid = $form_state['values']['field_product_type']['und'][0]['tid'];
    $type = taxonomy_term_load($type_tid)->name;
    $type_trimmed = mdmc_trim_string($type, 3);
    $type_trimmed_string = $type_trimmed . '-';
  } else {
    $type = '';
    $type_trimmed_string = '';
  }
  if (!empty($form_state['values']['field_product_sort']['und'][0]['tid'])) {
    $sort_tid = $form_state['values']['field_product_sort']['und'][0]['tid'];
    $sort = taxonomy_term_load($sort_tid)->name;
    $sort_trimmed = mdmc_trim_string($sort, 3);
    $sort_trimmed_string = $sort_trimmed . '-';
  } else {
    $sort = '';
    $sort_trimmed_string = '';
  }
  if (!empty($form_state['values']['field_product_variation']['und'][0]['name'])) {
    $variation = $form_state['values']['field_product_variation']['und'][0]['name'];
    $variation_trimmed = mdmc_trim_string($variation, 3);
    $variation_trimmed_string = $variation_trimmed . '-';
  } else {
    $variation = '';
    $variation_trimmed_string = '';
  }
  if (!empty($form_state['values']['field_product_size']['und'][0]['tid'])) {
    $size_tid = $form_state['values']['field_product_size']['und'][0]['tid'];
    $size = taxonomy_term_load($size_tid)->name;
    $size_trimmed = mdmc_trim_string($size, 3);
    $size_trimmed_string = $size_trimmed . '-';
  } else {
    $size = '';
    $size_trimmed_string = '';
  }
  if (!empty($form_state['values']['field_product_colour']['und'][0]['name'])) {
    $colour = $form_state['values']['field_product_colour']['und'][0]['name'];
    $colour_trimmed = mdmc_trim_string($colour, 3);
    $colour_trimmed_string = $colour_trimmed . '-';
  } else {
    $colour = '';
    $colour_trimmed_string = '';
  }
  if (!empty($form_state['values']['field_product_empty_case']['und'][0]['tid'])) {
    $emptycase_tid = $form_state['values']['field_product_empty_case']['und'][0]['tid'];
    $emptycase = taxonomy_term_load($emptycase_tid)->name;
    $emptycase_trimmed = mdmc_trim_string($emptycase, 1);
    $emptycase_trimmed_string = $emptycase_trimmed . '-';
  } else {
    $emptycase = '';
    $emptycase_trimmed_string = '';
  }
  //Build sku and title values and strings.
  $sku = $supplier_trimmed_string . $type_trimmed_string . $sort_trimmed_string . $variation_trimmed_string . $size_trimmed_string . $colour_trimmed_string . $emptycase_trimmed_string . '1';
  
  $title = (!empty($sort) ? $sort . ' ' : '') . (!empty($variation) ? '"' . $variation . '" ' : '') . (!empty($size) ? $size . ' ' : '') . (!empty($colour) ? $colour : '');
  //Set the sku and title value to the form-state
  form_set_value($form['sku'], $sku, $form_state);
  form_set_value($form['title'], $title, $form_state);
}

//function to make strings uppercase and trim to the first 3 positions.
function mdmc_trim_string($string, $number) {
  if (!empty($string)) {
    $string = strtoupper(mb_substr($string, 0, $number));
    return $string;
  }
}
